export const LOAD_DASHBOARDINFO_SUCCESS = 'LOAD_DASHBOARDRECORDS_SUCCESS';
export const LOAD_TRANSACTONTYPE_SUCCESS = 'LOAD_TRANSACTONTYPE_SUCCESS';
export const LOAD_TRANSACTIONS_SUCCESS = 'LOAD_TRANSACTIONS_SUCCESS';
export const LOAD_PERSONS_SUCCESS = 'LOAD_PERSONS_SUCCESS';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';

